//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription(".Net client for the Consul service registry")]
[assembly: AssemblyCompany("CPI Card Group, Inc.")]
[assembly: AssemblyProduct("Consul")]
[assembly: AssemblyVersion(".0")]
[assembly: AssemblyFileVersion(".0")]

